import { useState } from 'react';

export default function ExportReportModal({ data, isOpen, onClose }) {
  if (!isOpen || !data) return null;

  const now = new Date().toISOString();
  const filename = `vartha_cyclone_report_${now.replace(/[:.]/g, '-')}.json`;

  const reportPayload = {
    system_name: data.meta?.systemName || "Cyclone System",
    basin: data.meta?.basin || "North Indian Ocean",
    report_generated_utc: now,
    stage_01_detection: {
      model: data.provenance?.sources?.detection || "MobileNetV3 E9-2 candidate",
      detected: data.detection?.detected,
      confidence_pct: data.detection?.confidence,
      structural_pattern: data.detection?.structuralPattern || data.classification?.structuralPattern,
      source_frame: data.satellite?.source,
      localization_status: "Unavailable (no trained bounding-box localizer in bundle)",
    },
    stage_02_classification: {
      model: "LightGBM MultiSource Tabular / ResNet18 Image Classifier",
      category: data.classification?.category,
      scale: data.classification?.scale || "IMD",
      sustained_wind_kmh: data.classification?.windSpeedKmh,
      central_pressure_hpa: data.classification?.pressureHpa,
      confidence_pct: data.classification?.confidence,
    },
    stage_03_forecast: {
      model: "EXP005 GRU+Huber (Phase 5 Champion)",
      horizons: data.forecast?.map(f => ({
        horizon: f.label || `+${f.hour}h`,
        latitude: f.lat,
        longitude: f.lon,
        predicted_wind_kmh: f.windSpeedKmh,
      })),
      landfall_estimate: data.landfall,
    },
    provenance: data.provenance,
    disclaimer: "RESEARCH PROTOTYPE DEVELOPED FOR SIH 2026. This system is not an official meteorological warning service. Outputs are generated by offline experimental ML models."
  };

  function handleDownloadJSON() {
    const blob = new Blob([JSON.stringify(reportPayload, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }

  function handlePrintPDF() {
    window.print();
  }

  return (
    <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/70 backdrop-blur-sm p-4 print:p-0 print:bg-white">
      <div className="bg-cream border border-border rounded-2xl shadow-2xl max-w-2xl w-full max-h-[90vh] flex flex-col overflow-hidden print:border-none print:shadow-none print:max-h-full">
        
        {/* Fixed Header */}
        <div className="flex items-start justify-between border-b border-border p-5 bg-card/50 shrink-0">
          <div>
            <div className="text-[10px] uppercase font-bold text-accent-strong tracking-wider font-mono">
              SIH 2026 · AI Meteorological Intelligence
            </div>
            <h2 className="font-serif text-[20px] font-bold text-ink mt-0.5">
              Comprehensive Cyclone Analysis Report
            </h2>
          </div>
          <button
            onClick={onClose}
            className="text-ink-soft hover:text-ink text-2xl font-bold w-8 h-8 rounded-lg hover:bg-card-alt flex items-center justify-center print:hidden cursor-pointer"
          >
            ×
          </button>
        </div>

        {/* Scrollable Report Content */}
        <div className="flex-1 overflow-y-auto p-5 space-y-4 text-[12px] text-ink">
          
          {/* Metadata Block */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-card-alt p-3.5 rounded-xl border border-border/50 font-mono text-[11px]">
            <div>
              <span className="text-ink-faint text-[9px] uppercase font-sans font-bold block mb-0.5">Target System</span>
              <span className="font-bold text-ink leading-tight block">{data.meta?.systemName}</span>
            </div>
            <div>
              <span className="text-ink-faint text-[9px] uppercase font-sans font-bold block mb-0.5">Basin</span>
              <span className="font-bold text-ink leading-tight block">{data.meta?.basin}</span>
            </div>
            <div>
              <span className="text-ink-faint text-[9px] uppercase font-sans font-bold block mb-0.5">Current Category</span>
              <span className="font-bold text-accent-strong leading-tight block break-words">{data.classification?.category}</span>
            </div>
            <div>
              <span className="text-ink-faint text-[9px] uppercase font-sans font-bold block mb-0.5">Pass Timestamp</span>
              <span className="text-ink-soft leading-tight block">{data.meta?.lastPass ? new Date(data.meta.lastPass).toISOString().substring(0, 16).replace('T', ' ') + ' UTC' : "Recent"}</span>
            </div>
          </div>

          {/* Model Findings Summary */}
          <div className="space-y-2">
            <h3 className="font-serif font-bold text-[14px] text-ink border-b border-border/40 pb-1">
              Multi-Stage ML Prediction Findings
            </h3>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
              <div className="bg-card border border-border/60 rounded-xl p-3 space-y-1">
                <span className="text-[9.5px] font-bold uppercase tracking-wider text-ink-faint block">Satellite Detection</span>
                <div className="font-bold text-[13px]">
                  {data.detection?.detected ? "Cyclone Detected" : "No System"} ({data.detection?.confidence}%)
                </div>
                <div className="text-[10.5px] text-ink-soft font-mono">
                  Pattern: {data.detection?.structuralPattern || data.classification?.structuralPattern || "shear_pattern"}
                </div>
              </div>

              <div className="bg-card border border-border/60 rounded-xl p-3 space-y-1">
                <span className="text-[9.5px] font-bold uppercase tracking-wider text-ink-faint block">Current Intensity</span>
                <div className="font-bold text-[13px] text-accent-strong">
                  {data.classification?.windSpeedKmh} km/h
                </div>
                <div className="text-[10.5px] text-ink-soft font-mono">
                  Pressure: {data.classification?.pressureHpa} hPa ({data.classification?.confidence}% conf)
                </div>
              </div>

              <div className="bg-card border border-border/60 rounded-xl p-3 space-y-1">
                <span className="text-[9.5px] font-bold uppercase tracking-wider text-ink-faint block">24-Hour Forecast</span>
                <div className="font-bold text-[13px]">
                  {data.forecast?.[data.forecast.length - 1]?.lat.toFixed(2)}°N, {data.forecast?.[data.forecast.length - 1]?.lon.toFixed(2)}°E
                </div>
                <div className="text-[10.5px] text-ink-soft font-mono">
                  Wind: {data.forecast?.[data.forecast.length - 1]?.windSpeedKmh} km/h
                </div>
              </div>
            </div>
          </div>

          {/* Landfall & Risk */}
          <div className="bg-card border border-border/60 rounded-xl p-3 space-y-1">
            <h4 className="font-bold text-[12px]">Landfall Assessment &amp; Coast Proximity</h4>
            <p className="text-[11px] text-ink-soft font-mono leading-relaxed">
              Estimated Distance to Coast: <strong className="text-ink">{data.landfall?.distanceToLandKm ?? "—"} km</strong> · Landfall Coordinates: <strong className="text-ink">{data.landfall?.latitude ? `${data.landfall.latitude}°N ${data.landfall.longitude}°E` : "Offshore / Not within threshold"}</strong>
            </p>
          </div>

          {/* Scientific Disclaimer */}
          <div className="p-3 bg-mist/40 border border-border-soft rounded-xl text-[10.5px] text-ink-soft leading-relaxed">
            <strong className="text-ink block mb-0.5">Scientific Honesty &amp; Limitations Notice:</strong>
            VARTHA is a research prototype developed for SIH 2026. This is not an official meteorological warning service. Outputs are generated by offline experimental ML models (E9-2 MobileNetV3, LightGBM, EXP005 GRU).
          </div>
        </div>

        {/* Fixed Actions Bar */}
        <div className="flex items-center justify-end gap-3 p-4 bg-card/60 border-t border-border shrink-0 print:hidden">
          <button
            onClick={onClose}
            className="text-[11.5px] font-semibold text-ink border border-border bg-card rounded-lg px-4 py-2 hover:bg-card-alt cursor-pointer"
          >
            Close
          </button>
          <button
            onClick={handleDownloadJSON}
            className="text-[11.5px] font-bold text-ink border border-accent/40 bg-accent-soft/50 rounded-lg px-4 py-2 hover:bg-accent-soft flex items-center gap-1.5 cursor-pointer shadow-sm"
          >
            <span>📥</span> Download JSON
          </button>
          <button
            onClick={handlePrintPDF}
            className="text-[11.5px] font-bold text-white bg-accent-strong rounded-lg px-4 py-2 hover:opacity-90 flex items-center gap-1.5 shadow-sm cursor-pointer"
          >
            <span>🖨️</span> Print / Save PDF
          </button>
        </div>

      </div>
    </div>
  );
}
